//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.15 at 02:56:19 ���� CST 
//


package com.ejushang.steward.ordercenter.domain.sfreq;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Cargo" maxOccurs="unbounded"/>
 *         &lt;element ref="{}AddedService" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="cargo_total_weight" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="custid" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="d_address" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="d_city" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="d_company" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="d_contact" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="d_county" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="d_mobile" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="d_province" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="d_tel" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="express_type" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="j_address" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="j_city" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="j_company" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="j_contact" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="j_county" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="j_mobile" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="j_province" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="j_tel" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="orderid" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="parcel_quantity" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="pay_method" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="remark" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="sendstarttime" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cargo",
    "addedService"
})
@XmlRootElement(name = "Order")
public class Order {

    @XmlElement(name = "Cargo")
    protected List<Cargo> cargo;
    @XmlElement(name = "AddedService")
    protected List<AddedService> addedService;
    @XmlAttribute(name = "cargo_total_weight")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String cargoTotalWeight;
    @XmlAttribute()
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String custid;
    @XmlAttribute(name = "d_address")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dAddress;
    @XmlAttribute(name = "d_city")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dCity;
    @XmlAttribute(name = "d_company")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dCompany;
    @XmlAttribute(name = "d_contact")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dContact;
    @XmlAttribute(name = "d_county")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dCounty;
    @XmlAttribute(name = "d_mobile")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dMobile;
    @XmlAttribute(name = "d_province")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dProvince;
    @XmlAttribute(name = "d_tel")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String dTel;
    @XmlAttribute(name = "express_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String expressType;
    @XmlAttribute(name = "j_address")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String jAddress;
    @XmlAttribute(name = "j_city")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String jCity;
    @XmlAttribute(name = "j_company")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String jCompany;
    @XmlAttribute(name = "j_contact")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String jContact;
    @XmlAttribute(name = "j_county")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String jCounty;
    @XmlAttribute(name = "j_mobile")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String jMobile;
    @XmlAttribute(name = "j_province")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String jProvince;
    @XmlAttribute(name = "j_tel")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String jTel;
    @XmlAttribute()
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String orderid;
    @XmlAttribute(name = "parcel_quantity")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String parcelQuantity;
    @XmlAttribute(name = "pay_method")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String payMethod;
    @XmlAttribute()
    @XmlSchemaType(name = "anySimpleType")
    protected String remark;
    @XmlAttribute()
    @XmlSchemaType(name = "anySimpleType")
    protected String sendstarttime;

    public void setCargo(List<Cargo> cargo) {
        this.cargo = cargo;
    }

    public void setAddedService(List<AddedService> addedService) {
        this.addedService = addedService;
    }

    /**
     * Gets the value of the cargo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cargo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCargo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cargo }
     * 
     * 
     */
    public List<Cargo> getCargo() {
        if (cargo == null) {
            cargo = new ArrayList<Cargo>();
        }
        return this.cargo;
    }

    /**
     * Gets the value of the addedService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addedService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddedService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddedService }
     * 
     * 
     */
    public List<AddedService> getAddedService() {
        if (addedService == null) {
            addedService = new ArrayList<AddedService>();
        }
        return this.addedService;
    }

    /**
     * Gets the value of the cargoTotalWeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCargoTotalWeight() {
        return cargoTotalWeight;
    }

    /**
     * Sets the value of the cargoTotalWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCargoTotalWeight(String value) {
        this.cargoTotalWeight = value;
    }

    /**
     * Gets the value of the custid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustid() {
        return custid;
    }

    /**
     * Sets the value of the custid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustid(String value) {
        this.custid = value;
    }

    /**
     * Gets the value of the dAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDAddress() {
        return dAddress;
    }

    /**
     * Sets the value of the dAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDAddress(String value) {
        this.dAddress = value;
    }

    /**
     * Gets the value of the dCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDCity() {
        return dCity;
    }

    /**
     * Sets the value of the dCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDCity(String value) {
        this.dCity = value;
    }

    /**
     * Gets the value of the dCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDCompany() {
        return dCompany;
    }

    /**
     * Sets the value of the dCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDCompany(String value) {
        this.dCompany = value;
    }

    /**
     * Gets the value of the dContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDContact() {
        return dContact;
    }

    /**
     * Sets the value of the dContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDContact(String value) {
        this.dContact = value;
    }

    /**
     * Gets the value of the dCounty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDCounty() {
        return dCounty;
    }

    /**
     * Sets the value of the dCounty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDCounty(String value) {
        this.dCounty = value;
    }

    /**
     * Gets the value of the dMobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDMobile() {
        return dMobile;
    }

    /**
     * Sets the value of the dMobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDMobile(String value) {
        this.dMobile = value;
    }

    /**
     * Gets the value of the dProvince property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDProvince() {
        return dProvince;
    }

    /**
     * Sets the value of the dProvince property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDProvince(String value) {
        this.dProvince = value;
    }

    /**
     * Gets the value of the dTel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTel() {
        return dTel;
    }

    /**
     * Sets the value of the dTel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTel(String value) {
        this.dTel = value;
    }

    /**
     * Gets the value of the expressType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpressType() {
        return expressType;
    }

    /**
     * Sets the value of the expressType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpressType(String value) {
        this.expressType = value;
    }

    /**
     * Gets the value of the jAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJAddress() {
        return jAddress;
    }

    /**
     * Sets the value of the jAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJAddress(String value) {
        this.jAddress = value;
    }

    /**
     * Gets the value of the jCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJCity() {
        return jCity;
    }

    /**
     * Sets the value of the jCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJCity(String value) {
        this.jCity = value;
    }

    /**
     * Gets the value of the jCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJCompany() {
        return jCompany;
    }

    /**
     * Sets the value of the jCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJCompany(String value) {
        this.jCompany = value;
    }

    /**
     * Gets the value of the jContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJContact() {
        return jContact;
    }

    /**
     * Sets the value of the jContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJContact(String value) {
        this.jContact = value;
    }

    /**
     * Gets the value of the jCounty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJCounty() {
        return jCounty;
    }

    /**
     * Sets the value of the jCounty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJCounty(String value) {
        this.jCounty = value;
    }

    /**
     * Gets the value of the jMobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJMobile() {
        return jMobile;
    }

    /**
     * Sets the value of the jMobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJMobile(String value) {
        this.jMobile = value;
    }

    /**
     * Gets the value of the jProvince property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJProvince() {
        return jProvince;
    }

    /**
     * Sets the value of the jProvince property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJProvince(String value) {
        this.jProvince = value;
    }

    /**
     * Gets the value of the jTel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJTel() {
        return jTel;
    }

    /**
     * Sets the value of the jTel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJTel(String value) {
        this.jTel = value;
    }

    /**
     * Gets the value of the orderid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * Sets the value of the orderid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderid(String value) {
        this.orderid = value;
    }

    /**
     * Gets the value of the parcelQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParcelQuantity() {
        return parcelQuantity;
    }

    /**
     * Sets the value of the parcelQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParcelQuantity(String value) {
        this.parcelQuantity = value;
    }

    /**
     * Gets the value of the payMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayMethod() {
        return payMethod;
    }

    /**
     * Sets the value of the payMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayMethod(String value) {
        this.payMethod = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemark(String value) {
        this.remark = value;
    }

    /**
     * Gets the value of the sendstarttime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendstarttime() {
        return sendstarttime;
    }

    /**
     * Sets the value of the sendstarttime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendstarttime(String value) {
        this.sendstarttime = value;
    }

}
