//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.21 at 02:35:05 ���� CST 
//


package com.ejushang.steward.ordercenter.domain.sfrsp.ordersearch;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.test4 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class SfOrderSearchRspObjectFactory {

    private final static QName _Head_QNAME = new QName("", "Head");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.test4
     * 
     */
    public SfOrderSearchRspObjectFactory() {
    }

    /**
     * Create an instance of {@link SfOrderSearchOrderResponse }
     * 
     */
    public SfOrderSearchOrderResponse createOrderResponse() {
        return new SfOrderSearchOrderResponse();
    }

    /**
     * Create an instance of {@link SfOrderSearchRspERROR }
     * 
     */
    public SfOrderSearchRspERROR createERROR() {
        return new SfOrderSearchRspERROR();
    }

    /**
     * Create an instance of {@link SfOrderSearchRspBody }
     * 
     */
    public SfOrderSearchRspBody createBody() {
        return new SfOrderSearchRspBody();
    }

    /**
     * Create an instance of {@link SfOrderSearchResponse }
     * 
     */
    public SfOrderSearchResponse createResponse() {
        return new SfOrderSearchResponse();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Head")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createHead(String value) {
        return new JAXBElement<String>(_Head_QNAME, String.class, null, value);
    }

}
