
package com.sf.integration.expressservice.service;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CommonServiceService", targetNamespace = "http://service.expressservice.integration.sf.com/", wsdlLocation = "http://bsp-ois.sf-express.com/bsp-ois/ws/expressService?wsdl")
public class CommonServiceService
    extends Service
{

    private final static URL COMMONSERVICESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://bsp-ois.sf-express.com/bsp-ois/ws/expressService?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        COMMONSERVICESERVICE_WSDL_LOCATION = url;
    }

    public CommonServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonServiceService() {
        super(COMMONSERVICESERVICE_WSDL_LOCATION, new QName("http://service.expressservice.integration.sf.com/", "CommonServiceService"));
    }

    /**
     * 
     * @return
     *     returns IService
     */
    @WebEndpoint(name = "CommonServicePort")
    public IService getCommonServicePort() {
        return (IService)super.getPort(new QName("http://service.expressservice.integration.sf.com/", "CommonServicePort"), IService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IService
     */
    @WebEndpoint(name = "CommonServicePort")
    public IService getCommonServicePort(WebServiceFeature... features) {
        return (IService)super.getPort(new QName("http://service.expressservice.integration.sf.com/", "CommonServicePort"), IService.class, features);
    }

}
