//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.21 at 02:32:24 ���� CST 
//


package com.ejushang.steward.ordercenter.domain.sfreq.ordersearch;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.test3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class SfOrderSearchReqObjectFactory {

    private final static QName _Head_QNAME = new QName("", "Head");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.test3
     * 
     */
    public SfOrderSearchReqObjectFactory() {
    }

    /**
     * Create an instance of {@link SfOrderSearchReq }
     * 
     */
    public SfOrderSearchReq createOrderSearch() {
        return new SfOrderSearchReq();
    }

    /**
     * Create an instance of {@link SfOrderSearchRequest }
     * 
     */
    public SfOrderSearchRequest createRequest() {
        return new SfOrderSearchRequest();
    }

    /**
     * Create an instance of {@link SfOrderSearchReqBody }
     * 
     */
    public SfOrderSearchReqBody createBody() {
        return new SfOrderSearchReqBody();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Head")
    public JAXBElement<String> createHead(String value) {
        return new JAXBElement<String>(_Head_QNAME, String.class, null, value);
    }

}
