//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.21 at 02:32:24 ���� CST 
//


package com.ejushang.steward.ordercenter.domain.sfreq.ordersearch;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}OrderSearch"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "sfOrderSearchReq"
})
@XmlRootElement(name = "Body")
public class SfOrderSearchReqBody {

    @XmlElement(name = "OrderSearch")
    protected SfOrderSearchReq sfOrderSearchReq;

    /**
     * Gets the value of the orderSearch property.
     * 
     * @return
     *     possible object is
     *     {@link SfOrderSearchReq }
     *     
     */
    public SfOrderSearchReq getSfOrderSearchReq() {
        return sfOrderSearchReq;
    }

    /**
     * Sets the value of the orderSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link SfOrderSearchReq }
     *     
     */
    public void setSfOrderSearchReq(SfOrderSearchReq value) {
        this.sfOrderSearchReq = value;
    }

}
